const AUTH_DOMAIN = import.meta.env.VITE_REACT_APP_AUTH_DOMAIN;
const CLIENT_ID = import.meta.env.VITE_REACT_APP_AUTH_CLIENT_ID;
const LOADING = import.meta.env.VITE_REACT_APP_LOADING_URI;

export { AUTH_DOMAIN, CLIENT_ID, LOADING};