POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "email": "david@gmail.com",
    "password": "123456789",
}

###

POST http://localhost:3001/api/users/

Content-Type: application/json

    {
    "email": "david@gmail.com",
    "password": "123456789",
    "role": "caregiver",
    "profilePicture": "/pictures/anny.png",
    "name": "David",
    "lastName": "X",
    "cellPhone": "+51910999999",
    "address": "Av los juarez",
    "dni": "0070239657",
    "birthdate": "04-08-2005"
  }
  