export const GET_OFFERS_OWNER = 'GET_OFFERS_OWNER';
export const GET_OFFERS_CAREGIVERS = 'GET_OFFERS_CAREGIVERS';

export const FILTER_OFFERS_OWNER = 'FILTER_OFFERS_OWNER';
export const SORT_OFFERS_OWNER = 'SORT_OFFERS_OWNER';